version: 2
jobs:
  build:
    docker:
      - image: circleci/python3.7

    working_directory: ~/CalculatorApp

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/Scripts/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
          . venv/Scripts/activate
          flake8 --exclude=venv* --statistics
          pytest -v --cov=calculator